// Batch down - auto-generated by runique
// Timestamp: 20260320_130926
// Tables: roadmap_entry
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("roadmap_entry"))
                    .drop_column(Alias::new("link_url_2"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("roadmap_entry"))
                    .drop_column(Alias::new("link_label_2"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
