// Batch down - auto-generated by runique
// Timestamp: 20260614_221003
// Tables: blog
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("blog"))
                    .drop_column(Alias::new("view_count"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("blog"))
                    .drop_column(Alias::new("status"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
