use runique::prelude::*;

model! {
    TestAllFields,
    table: "test_all_fields",
    pk: id => uuid,
    {
        f_text:            text,
        f_email:           email,
        f_url:             url,
        f_password:        password,
        f_textarea:        textarea,
        f_richtext:        richtext,
        f_integer:         int,
        f_float:           float,
        f_decimal:         text,
        f_percent:         percent,
        f_range:           int,
        f_checkbox:        bool,
        f_radio_single:    bool,
        f_select:          text,
        f_select_multiple: json,
        f_radio_group:     text,
        f_checkbox_group:  json,
        f_date:            date,
        f_time:            time,
        f_datetime:        datetime,
        f_duration:        bigint,
        f_file_image:      json,
        f_file_document:   json,
        f_file_any:        json,
        f_color:           color,
        f_slug:            slug,
        f_uuid:            uuid,
        f_json:            json,
        f_ip:              ip,
        created_at:        datetime [auto_now],
        updated_at:        datetime [auto_now_update],
    }
}
