use runique::prelude::*;

model! {
    TestAllFields,
    table: "test_all_fields",
    pk: id => uuid,
    {
        f_text:            text [nullable],
        f_email:           email [nullable],
        f_url:             url [nullable],
        f_password:        password [nullable],
        f_textarea:        textarea [nullable],
        f_richtext:        richtext [nullable],
        f_integer:         int [nullable],
        f_float:           float [nullable],
        f_decimal:         decimal [nullable],
        f_percent:         percent [nullable],
        f_range:           int [nullable],
        f_checkbox:        bool [nullable],
        f_radio_single:    bool [nullable],
        f_select:          text [nullable],
        f_select_multiple: json [nullable],
        f_radio_group:     text [nullable],
        f_checkbox_group:  json [nullable],
        f_date:            date [nullable],
        f_time:            time [nullable],
        f_datetime:        datetime [nullable],
        f_duration:        bigint [nullable],
        f_file_image:      json [nullable],
        f_file_document:   json [nullable],
        f_file_any:        json [nullable],
        f_color:           color [nullable],
        f_slug:            slug [nullable],
        f_uuid:            uuid [nullable],
        f_json:            json [nullable],
        f_ip:              ip [nullable],
        created_at:        datetime [auto_now],
        updated_at:        datetime [auto_now_update],
    },
    meta: {
        unique_together: [(f_text, f_integer)],
    }
}
