use runique::prelude::*;

model! {
    TestAllFields,
    table: "test_all_fields",
    pk: id => uuid,
    fields: {
        f_text: String [nullable],
        f_email: String [nullable],
        f_url: String [nullable],
        f_password: String [nullable],
        f_textarea: String [nullable],
        f_richtext: String [nullable],
        f_integer: i32 [nullable],
        f_float: String [nullable],
        f_decimal: String [nullable],
        f_percent: i32 [nullable],
        f_range: i32 [nullable],
        f_checkbox: bool [nullable],
        f_radio_single: bool [nullable],
        f_select: String [nullable],
        f_select_multiple: json [nullable],
        f_radio_group: String [nullable],
        f_checkbox_group: json [nullable],
        f_date: datetime [nullable],
        f_time: String [nullable],
        f_datetime: datetime [nullable],
        f_duration: i64 [nullable],
        f_file_image: json [nullable],
        f_file_document: json [nullable],
        f_file_any: json [nullable],
        f_color: String [nullable],
        f_slug: String [nullable],
        f_uuid: uuid [nullable],
        f_json: json [nullable],
        f_ip: String [nullable],
        created_at: datetime [auto_now],
        updated_at: datetime [auto_now_update],
    }
}
