// Batch down - auto-generated by sea-orm-builder
// Timestamp: 20260218_215952
// Tables: users_booster
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("users_booster"))
                    .drop_column(Alias::new("updated_at"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
