// Batch down - auto-generated by runique
// Timestamp: 20260923_215427
// Tables: test_all_fields
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_index(Index::drop().name("test_all_fields_f_text_f_integer_uniq").table(Alias::new("test_all_fields")).to_owned())
            .await?;
        Ok(())
    }
}
