// Batch down - auto-generated by sea-orm-builder
// Timestamp: 20260304_145358
// Tables: test_all_fields
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("test_all_fields"))
                    .add_column(ColumnDef::new(Alias::new("updated_at")).date_time().null())
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("test_all_fields"))
                    .add_column(ColumnDef::new(Alias::new("created_at")).date_time().null())
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
