// Batch down - auto-generated by runique
// Timestamp: 20260318_140518
// Tables: contributions
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_foreign_key(
                ForeignKey::drop()
                    .table(Alias::new("contributions"))
                    .name("contributions_user_id_eihwaz_users_fkey")
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
