// Batch down - auto-generated by runique
// Timestamp: 20260614_221003
// Tables: site_config
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("site_config"))
                    .drop_column(Alias::new("sort_order"))
                    .to_owned(),
            )
            .await?;

        manager
            .alter_table(
                Table::alter()
                    .table(Alias::new("site_config"))
                    .drop_column(Alias::new("is_public"))
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}
