//! Debug error message key constants injected into templates.

pub const DEBUG_MESSAGE_KEYS: &[&str] = &[
    "debug_info_title",
    "debug_field_title",
    "debug_field_count",
    "debug_error_count",
    "debug_main_message",
    "debug_root_cause",
    "debug_details",
    "debug_request_info",
    "debug_http_method",
    "debug_path",
    "debug_query_params",
    "debug_http_headers",
    "debug_template_info",
    "debug_template_name",
    "debug_error_line",
    "debug_template_source",
    "debug_available_templates",
    "debug_stack_trace_title",
    "debug_stack_trace_tip",
    "debug_environment",
    "debug_debug_mode",
    "debug_enabled",
    "debug_disabled",
    "debug_rust_version",
    "debug_app_version",
    "debug_status_code",
    "debug_header_name",
    "debug_header_value",
];
